---
- hosts: pi
  become: yes
  vars:
    http_port: 22
    max_clients: 5
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
  - name: update the system
    apt:
      upgrade: dist
      update_cache: yes
  - name: install postgres
    apt:
      name: postgresql
      state: latest
  - name: install git
    apt:
      name: git
      state: latest
  - name: install java
    apt:
      name: openjdk-8-jdk
      state: latest
  - name: create user
    shell: createuser root -s
    become_user: postgres
    ignore_errors: true
  - name: create database
    shell: createdb localmovies
    become_user: postgres
    ignore_errors: true
  - name: install maven
    apt:
      name: maven
      state: latest
  - name: remove old files
    shell: rm -rf /home/pi/*
  - git:
      repo: https://github.com/rahmnathan/LocalMovies---LinuxServer.git
      dest: /home/pi/LocalMovies
  - name: build project
    shell: chdir=/home/pi/LocalMovies mvn install
  - name: stop server (if it's running)
    shell: pkill -f 'spring'
    ignore_errors: yes
  - name: start server
    shell: chdir=/home/pi/LocalMovies/RestServer mvn spring-boot:run &
